### ISSUE TITLE
Left-side navbar: useful or confusing?

### ISSUE THREAD

**Issue by eguiraud** [root-project/web#8] opened 2020-06-03 13:22 UTC
Hi,
I would like to hear what people think about the left side navbar that you find e.g. [here](https://root.s3-website.cern.ch/web/download).

I often find it very confusing, mostly because there seems to be no consistency to what its contents are: sometimes [it looks like it describes a subsection of the site](https://root.s3-website.cern.ch/web/manual), but it actually also contains links to other parts or the site. Sometimes it [mirrors the page contents](https://root.s3-website.cern.ch/web/for_developers) or the table of content (that is  _also_ present), sometimes it actually looks like it's for [navigating a sub-section of the website](https://root.s3-website.cern.ch/web/about), but it adds _slightly different_ links than the actual page content.

Solutions I can think of:

* consistently use the left-side navbar to describe and link to sub-sections of the website, e.g. under `/about`, only link to `/about/license`, `/about/team`, `/about/...`, and in other pages such as `/get_started`, that do not have sub-pages, just remove the left-side navbar
* consistently use the left-side navbar for a _flat_ list of a few "useful links" per page (and title it "useful links")

EDIT:
to make things more confusing, on small screens the navbar disappears under a button that calls it a "menu"

**Comment by couet** [comment] 2020-06-03 13:51
I personnel find the left side nav bar very useful well you are in a given topic on the web site. The one you point is about downloading. May be it can be improved.

**Comment by Axel-Naumann** [comment] 2020-06-03 13:56
How is the content for the navbar defined? Manually? Then I guess we should have rules about what show up there (vs TOC), and clearly mark external links (e.g. https://i.stack.imgur.com/1vy9x.png)

**Comment by eguiraud** [comment] 2020-06-03 13:59
> The one you point is about downloading

Uhm I linked to four different navbars and for the last three I described what's wrong with them in detail..

**Comment by vepadulano** [comment] 2020-06-03 16:00
I believe the "useful links" idea would require some time to figure out what links to put in each page to make it consistent and non-redundant, but I prefer it in the end because it would be more practical for the end user to find what they were looking for more quickly. For example, the [Manual](https://root.s3-website.cern.ch/web/manual) page could show the "other learning resources" links on the left navbar. 

Furthermore, I personally find that the navbar doesn't stand out, maybe putting it in a box or darkening the font color would help.

In any case, I would avoid showing two nav-bars (e.g. [here](https://root.s3-website.cern.ch/web/for_developers) ).

**Comment by eguiraud** [comment] 2020-06-09 14:37
After discussion with @couet and others, my opinion is that in some sections, such as /install, the left-side navbar should only contain a handful of useful links, be small and flat and titled "useful links".
In other sections, such as /manual, the left-side navbar can really be a map of the section you are in, but then the ToC should not appear on the right (see https://root-project.github.io/web/manual/getting_started_with_root/ for how it can get confusing) but instead be embedded in the navbar as @claireguyot was suggesting.

The button that hides the navbar on small screens should not call it "menu" but "useful links" or similar.

With this said, I am not sure what's the set of deliverables that we want for the milestone.

**Comment by Axel-Naumann** [comment] 2020-06-15 15:22
For the release, we will update the navbar of all pages, to adhere to the following guidelines:

- no dupe of navbar entries and page's TOC
- navbar should contain short, flat list of links ("useful links")
- separate out the section's TOC; for now keep it in the left navbar; do not repeat the TOC entries

**Comment by eguiraud** [comment] 2020-06-16 14:32
In the current version of the website, when the navbar does not contain a flat list of useful links, it's because it contains the section's ToC. I'll remove the "Publication" milestone as I think most of the issue has been addressed.

**Closed** 2020-09-29 19:28 UTC
Labels: discussion
