### ISSUE TITLE
unseen reply at a blog post

### ISSUE THREAD

**Issue by ynikitenko** [root-project/web#582] opened 2021-05-17 12:44 UTC
When I open the most recent blog post (https://root.cern/blog/624-and-2021/), in the end there is a grey *1 reply* line. However, I can't see the reply (neither from Firefox, which is rather old for me now, nor from Google Chrome).

It should be possible to see the reply or it should not show that there are any, if they don't exist.

P.S. Font increasing/decreasing doesn't help. Firefox 63.0.3 (64-bit).

**Comment by eguiraud** [comment] 2021-05-17 12:57
Bit of a weird thing, there is one message but it's a system message: https://root-forum.cern.ch/t/root-news-v6-24-what-2021-will-bring-and-a-surprise/44741 . It's a quirk of the web/forum integration.

**Comment by eguiraud** [comment] 2021-07-07 14:34
Closing as "not a bug", I think we can live with this

**Closed by eguiraud** 2021-07-07 14:34 UTC
